### ISSUE TITLE
Does it require javascript to work?

### ISSUE THREAD

**Issue by sausin** [Wikiki/bulma-switch#1]
First off thanks for the awesome work with the extensions!!

I just tried the switch in my project and the checkbox just remains as it was (i.e. it makes no difference to the state of the checkbox when I click on it).

I saw that you're using "id" on the form field. Does that mean it requires javascript for it to work?

If you could please advise.

Thanks!
Saurabh

**Comment by sausin** [comment]
Below in action:

![manual-adjustment-brings-hazard-sign](https://user-images.githubusercontent.com/11542923/30002058-5bb044d6-90a0-11e7-8c69-2f28d681c187.gif)

**Comment by Wikiki** [comment]
Hi @sausin,

This extension is pure CSS. No JavaScript needed.

Please just respect the following strucure:
```html


<div class="field">
  <input id="switchExample" type="checkbox" name="switchExample" class="switch" checked="checked">
  <label for="switchExample">Switch example</label>
</div>
```

the <code>for</code> attribute is mandatory. It will link the label to the checkbox and then  manage the style. This attribute need to be set up with the id attribute of the checkbox input (in my example switchExample).

Let me know if it's ok.

Regards

**Comment by sausin** [comment]
@Wikiki Thanks! Including the id and for makes it work properly!!

Once again, thanks a lot for your work on these extensions!

**Comment by Wikiki** [comment]
Thank you.

For information I have updated the documentation to give information about id and for attributes.

Regards
