### ISSUE TITLE
Remove on selected outline

### ISSUE THREAD

**Issue by angrykoala** [Wikiki/bulma-switch#18]
When selected, the labels making the switch button show an outline
![screenshot from 2018-05-28 01-25-01](https://user-images.githubusercontent.com/5960567/40591697-230c3fa2-6216-11e8-8d6c-077c4eddcfb8.png)
Could it be possible to set it to none so it doesn't show each time the switch is clicked?

**Comment by Wikiki** [comment]
Hi, this style is applied on focus only.
You can customize <code>$switch-focus</code> Sass variable to change it.
