### ISSUE TITLE
Make label optional

### ISSUE THREAD

**Issue by Jomik** [Wikiki/bulma-switch#2]
So, label is required, as I realized after messing around with this for a while. I don't want a label on my switches though, as I use them in a table layout, the "label" is given by the table head.

I did workaround it by simply adding an empty label, however I think the label should be optional, if possible.
```
<input type="checkbox" class="switch" :id="index+col" v-modal="list[col]">
<label :for="index+col"></label>
```

**Comment by Wikiki** [comment]
Hi @Jomik,

Indeed, Label is mandatory due to the fact that is the label which is designed to display the switch using ::after and ::before.

An empty Label is the way to not have any text.

I did not find any way to not use a label without using JS.

Regards

**Comment by Jomik** [comment]
That is fair enough! The switch does not show up without a label, was my issue.
