### ISSUE TITLE
Check box dotted border

### ISSUE THREAD

**Issue by davidbudnick** [Wikiki/bulma-switch#20]
Can you add this css code as an option to remove the dotted border on a switch?

.switch[type='checkbox'] + label::before,
.switch[type='checkbox']:checked + label:before {
  outline: none;
}
.switch[type='checkbox'] + label::after,
.switch[type='checkbox']:checked + label:after {
  outline: none;
}

As seen here:
![selection_031](https://user-images.githubusercontent.com/18271248/41744862-b16c91fe-756a-11e8-8875-3fe8afc7568e.png)

Thanks,
David

**Comment by Wikiki** [comment]
Hi,

it's already an option.
Just change the <code>$checkradio-focus</code> Sass variable to <code>none</code> and recompile sources using <code>gulp</code> ;-)

**Comment by davidbudnick** [comment]
Thanks!
