### ISSUE TITLE
Slider object not displayed

### ISSUE THREAD

**Issue by pkbarbiedoll** [Wikiki/bulma-switch#21]
When I include bulma-switch.min.css in my project file and use the following input: 

```
<link rel="stylesheet" href="/css/bulma-switch.min.css">
<div class="field">		
	<label class="label" for="switchExample">Click Me</label>
	<input type="checkbox" name="clickme" class="switch" id="switchExample">
</div>
```

The switch does not display (neither does a plain checkbox).   No errors show in the console and bulma-switch.min.css is accessible if I access it directly.   I'm using Bulma 0.6.2. 

Apart from Bulma itself, are there other resources that are required for the switch extension to work correctly?    I installed by simply copying bulma-switch.min.css to the server path in the link tag above.

**Comment by rangermeier** [comment]
The order of HTML tags matter. The` <label>` has to be directly after the `<input>`, e.g.

```
<div class="field">
    <input type="checkbox" name="clickme" class="switch" id="switchExample">
    <label class="label" for="switchExample">Click Me</label>
</div>
```
