### ISSUE TITLE
About import bulma-switch into angular project

### ISSUE THREAD

**Issue by DarielCC** [Wikiki/bulma-switch#3]
Hello, I'm trying to use the bulma-switch inside my angular project, install bulma-extensions through npm, but I do not know how to reference the bulma-switch for my css to work

**Comment by Wikiki** [comment]
Hi @DarielCC ,

I only provide sass file and not precompiled version (it's in progress).
So you can't import css directly. Instead you have to import sass version (using <code>~bulma-switch/switch</code>).

Regards
