### ISSUE TITLE
input checkbox absolute position not always correct

### ISSUE THREAD

**Issue by wazowsk1** [Wikiki/bulma-switch#4]
The checkbox input for the switch is currently marked with the absolute position which causes it to not always position itself correctly on the page

![image](https://user-images.githubusercontent.com/10253291/31026887-5e89b8ec-a548-11e7-862c-1859c0dd3195.png)

Current css
```
.switch[type="checkbox"] {
   outline: 0;
   user-select: none;
   position: absolute;
   margin-bottom: 0;
   opacity: 0;
   left: 0;
}
```
Is it not easier to just use a display:none? or the parent div (field) should be position:relative. 

This works so far better in this case.
```
.switch[type="checkbox"] {
    display: none;
}
```

**Comment by Wikiki** [comment]
Hi @wazowsk1 ,

you're right, <code>display: none</code> to the job perfectly.

Thanks for this.

Regards
