### ISSUE TITLE
Checked attribute doesn't work by default

### ISSUE THREAD

**Issue by NPJigaK** [Wikiki/bulma-switch#45]
hello. @Wikiki 

I found Bug

Use CDN.
```
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.0/css/bulma.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-switch@2.0.0/dist/css/bulma-switch.min.css">
```

Regardless of whether it is set to `checked="checked"` or `checked=""`, it is always displayed as checked.

When you check the DOM, it becomes `checked="checked"` . (In HTML, `checked=""`  is used)

Thank you.

**Comment by TBury** [comment]
@KagiJPN Found a workaround: simple uncheck the switch with Javascript when loading page.
Have this bug, too, same versions of components, Firefox 75. I hope that it'll be fixed soon.
@Wikiki

**Comment by HDRamosMendoza** [comment]
> hello. @Wikiki
> 
> I found Bug
> 
> Use CDN.
> 
> ```
>     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.0/css/bulma.css">
>     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-switch@2.0.0/dist/css/bulma-switch.min.css">
> ```
> 
> Regardless of whether it is set to `checked="checked"` or `checked=""`, it is always displayed as checked.
> 
> When you check the DOM, it becomes `checked="checked"` . (In HTML, `checked=""` is used)
> 
> Thank you.

Add => link rel "stylesheet" href="https://wikiki.github.io/css/documentation.css?v=201911011043"

**Comment by HDRamosMendoza** [comment]
https://hdramosmendoza.github.io/Frontend/Widget/Proyectos/index.html
