### ISSUE TITLE
The default checkbox is displayed. 

### ISSUE THREAD

**Issue by stefann01** [Wikiki/bulma-switch#47]
Hello! I used the example provided in the documentation:
![image](https://user-images.githubusercontent.com/30937067/79905343-c22f8180-841e-11ea-9247-867bef2e22a8.png)
I have also installed it with npm, but the default(primitive) checkbox is displayed:
![image](https://user-images.githubusercontent.com/30937067/79905466-f9059780-841e-11ea-953c-590865b239f4.png)

**Comment by CreativeBulma** [comment]
Hi,

how did you import stylesheet ?

**Comment by stefann01** [comment]
I use it in an Angular application. I have the styles in the angular.json like this:
![image](https://user-images.githubusercontent.com/30937067/79908713-636d0680-8424-11ea-8ced-7488d23b2973.png)

**Comment by stefann01** [comment]
Also, in the documentation (https://wikiki.github.io/form/switch/) it's only specify that same value should be provided for id and for

**Comment by CreativeBulma** [comment]
I think you forgot to import bulma-switch CSS file: `/node_modules/bulma-switch/dist/css/bulma-switch.min.css`.

Installation steps are detailed here: https://wikiki.github.io/

**Comment by stefann01** [comment]
Yep. I forgot to add this to styles.css file:
@import 'bulma';
@import '~bulma-switch';
Thanks!
