### ISSUE TITLE
Switch is not displayed

### ISSUE THREAD

**Issue by fabioinfo44** [Wikiki/bulma-switch#53]
I downloaded _bulma-switch.min.css_ and added `<link rel="stylesheet" href="/bulma-switch.min.css">` in my HTML, but using `<input type="checkbox" class="switch" checked="checked">`  no switch is displayed.

**Comment by HDRamosMendoza** [comment]
> I downloaded _bulma-switch.min.css_ and added `<link rel="stylesheet" href="/bulma-switch.min.css">` in my HTML, but using `<input type="checkbox" class="switch" checked="checked">` no switch is displayed.

link rel "stylesheet" href="https://wikiki.github.io/css/documentation.css?v=201911011043"

**Comment by HDRamosMendoza** [comment]
https://hdramosmendoza.github.io/Frontend/Widget/Proyectos/index.html

**Comment by fabioinfo44** [comment]
Solved, just added the label which seems to be necessary
