### ISSUE TITLE
form post

### ISSUE THREAD

**Issue by fabioinfo44** [Wikiki/bulma-switch#54]
I have developed a form (POST method) which contains some switches, but they send "on" and nothing instead of "true" and "false".

**switch example**
`<div class="field">
                      <div class="control">
                        <input id="meas-hum" type="checkbox" name="meas-hum"
                          class="switch is-info is-rounded is-outlined" checked>
                        <label for="meas-hum" class="switch-label"></label>
                      </div>
                    </div>`

**switch handling function** 
`document.querySelectorAll(".switch").forEach(function (swt) {
      swt.addEventListener("click", function (e) {
        swt.value = swt.checked;
      });
    });`

**Comment by Wikiki** [comment]
Are you using Laravel as backend ?
Seems more related to your framework which handle request than the package (bulma-switch does not change browser/framework behavior only design).

**Comment by fabioinfo44** [comment]
I am running this website on a development board (ESP8266) and I am correctly getting all the parameters of the post request (considered that the form has also text inputs) apart from those

**Comment by Wikiki** [comment]
The value "on" is the default one (If the value is not otherwise specified, it is the string on by default). See: https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/checkbox for more understanding on how checkboxes are working.

**Comment by fabioinfo44** [comment]
I know but my javascript code was supposed to change switches' value depending on their checked or not attribute.
Doesn't it? How should it be changed?

**Comment by Wikiki** [comment]
not sure you can dynamiccally change a checkbox value this way. because the value is sent only if checkbox is checked. if not, no value at all for this element will be sent with the form. so you can try setting true/false as value and check if meas-hum is true/false because meas-hum will not be set in form data if not checked.

**Comment by fabioinfo44** [comment]
unfortunately I cannot do that, I need some kind of javascript handling
