### ISSUE TITLE
Indentation 2 levels deeper causes sass compile error

### ISSUE THREAD

**Issue by bstashio** [Wikiki/bulma-switch#6]
Hello

Here's the error that `sass` throws when used in a terminal:

```
Error: The line was indented 2 levels deeper than the previous line.
        on line 156 of bulma-switch/switch.sass

151:     &.is-unchecked-#{$name}
152:       + label
153:         &::before
154:           background: $color
155:       &.is-outlined
156:           + label
157:             &::before
158:               background-color: transparent
159:               border-color: $color !important
160:             &::after
161:               background: $color
```

May I suggest that you use [travis-ci](https://travis-ci.org/), or any other CI tool, similar to how we used it in [bulma](https://github.com/bstashio/bulma/blob/master/.travis.yml), so that it detects such errors before merging.

**Comment by Wikiki** [comment]
Thanks.
I've copied your Travis config btw.

**Comment by bstashio** [comment]
Great!

Now I can update your extensions in customizer.
