### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by h0r1zon** [Wikiki/bulma-switch#8]
So when trying to use the switches, I come across this issue where if I click a certain area that isn't the switch, it triggers anyways. It also adds some large extra white space that I did not intend for. http://prntscr.com/h99q8m
http://prntscr.com/h99qvn

**Comment by h0r1zon** [comment]
Nevermind, I fixed it by removing the div.

**Comment by Laraveldeep** [comment]
I am having the same issue. It inserts big white space below footer. Extra white space goes away if I remove the `<div class="field">` but it is triggering even if I click on different part of the screen. Can't even click my menu.  Any suggestion?

**Comment by Wikiki** [comment]
Hi,

Can you please provide a codepen for your usecase ?

**Comment by Laraveldeep** [comment]
https://codepen.io/Laraveldeep/pen/rYGYWq

Can't find a way to include extensions. Basically I am trying to include switch inside media object to toggle users posts active and inactive.

**Comment by Wikiki** [comment]
My bad I fotgot to commit last updates.
It done and your issue should be fixed now.

**Comment by Laraveldeep** [comment]
I updated to new version and that solved the issue. No need to remove div either.

Thanks!
