### ISSUE TITLE
Make package include the compiled CSS

### ISSUE THREAD

**Issue by szokodiakos** [Wikiki/bulma-switch#9]
Hi There

First of all, awesome project! My question is that could it be possible to include the compiled CSS in the NPM package, so that if I don't use SASS at all I can easly import the minified CSS for my project?

For example when I'd like to use Font Awesome, all I have to do is import their bundled CSS like:
```
import 'font-awesome/css/font-awesome.min.css';
```

Thanks!

**Comment by Wikiki** [comment]
Hi,

packages now include CSS and minified CSS files
